---
- hosts: SWITCH
  gather_facts: false
  connection: ansible.netcommon.network_cli
  become: yes

  vars:
    upgrade_ios_version: 15.2(7)E5

  tasks:
    - name: enable scp server
      cisco.ios.ios_config:
        lines:
          - no ip scp server enable
          - no aaa authorization exec default group SRV-RD-GROUP

    - name: Change Boot Variable to new image
      ios_config:
        commands:
          - "boot system flash:c2960x-universalk9-mz.152-7.E5.bin"
        save_when: always

    - name: Reload the Device
      cli_command:
        command: reload
        prompt:
          - confirm
        answer:
          - 'y'




