---
- hosts: SWITCH
  gather_facts: false
  connection: ansible.netcommon.network_cli
  become: yes

  vars:
    upgrade_ios_version: 15.2(7)E5

  tasks:
    - name: CHECK CURRENT VERSION OF SWITCH
      cisco.ios.ios_facts:

    - name: Printa informacoes sobre atualizacao e versao atual do dispositivo
      debug:
        msg:
        - "The model of switch is {{ ansible_net_model }}"
        - "Current version of switch is {{ ansible_net_version }}"
        - "Upgrade image is {{ upgrade_ios_version }}"

    - name: Print msg if image is not compliant
      debug:
        msg:
        - "Image is not compliant and need to be upgraded"

      when: ansible_net_version != upgrade_ios_version

    - name: Print msg if image is compliant
      debug:
        msg:
        - "Image is compliant"

      when: ansible_net_version == upgrade_ios_version

    - name: CANCELA ATUALIZACAO CASO JA ESTEJA NA VERSAO CORRETA
      meta: end_play
      when: ansible_net_version == upgrade_ios_version

## Create backup folder for today

- hosts: localhost

  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

        - name: Create Directory {{hostvars.localhost.DTG}}
      file:
        path: ~/network-programmability/backups/{{hostvars.localhost.DTG}}
        state: directory
  run_once: true


- hosts: SWITCH
  gather_facts: false
  connection: ansible.netcommon.network_cli
  become: yes

  tasks:
    - name: Backup Running Config
      ios_command:
        commands: show tech
      register: config
      vars:
        ansible_command_timeout: 120

    - name: Save output to ~/network-programmability/backups/
      copy:
        content: "{{config.stdout[0]}}"
        dest: "~/network-programmability/backups/{{hostvars.localhost.DTG}}/{{ inventory_hostname }}-{{hostvars.localhost.DTG}}-config.txt"

    - name: enable scp server
      cisco.ios.ios_config:
        lines:
          - ip scp server enable
          - aaa authorization exec default group SRV-RD-GROUP

## SAVE the Running Config

    - name: Save running config
      ios_config:
        save_when: always

    - name: Copy Image // This could take up to 4 minutes
      net_put:
        src: "/etc/ansible/installapps/c2960x-universalk9-mz.152-7.E5.bin"
        dest: "flash:/c2960x-universalk9-mz.152-7.E5.bin"
      vars:
        ansible_command_timeout: 2200
